version: "3.9"

services:
  naca.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=User ID=postgres;Password=postgres;Server=postgres;Database=ca-template-db;Pooling=true;
      - RabbitMQConfiguration__UserName=admin
      - RabbitMQConfiguration__Password=admin
      - RabbitMQConfiguration__Host=rabbitmq
      - Serilog__WriteTo__1__Name=Seq
      - Serilog__WriteTo__1__Args__serverUrl=http://seq:80

  naca.worker:
    environment:
      - DOTNET_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=User ID=postgres;Password=postgres;Server=postgres;Database=ca-template-db;Pooling=true;
      - RabbitMQConfiguration__UserName=admin
      - RabbitMQConfiguration__Password=admin
      - RabbitMQConfiguration__Host=rabbitmq
      - Serilog__WriteTo__1__Name=Seq
      - Serilog__WriteTo__1__Args__serverUrl=http://seq:80

  naes.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - EventStore__ConnectionString=PORT = 5432; HOST = postgres; TIMEOUT = 15; POOLING = True; MINPOOLSIZE = 1; MAXPOOLSIZE = 100; COMMANDTIMEOUT = 20; DATABASE = es-template-db; PASSWORD = postgres; USER ID = postgres
      - RabbitMQConfiguration__UserName=admin
      - RabbitMQConfiguration__Password=admin
      - RabbitMQConfiguration__Host=rabbitmq
      - Serilog__WriteTo__1__Name=Seq
      - Serilog__WriteTo__1__Args__serverUrl=http://seq:80

  naes.worker:
    environment:
      - DOTNET_ENVIRONMENT=Development
      - EventStore__ConnectionString=PORT = 5432; HOST = postgres; TIMEOUT = 15; POOLING = True; MINPOOLSIZE = 1; MAXPOOLSIZE = 100; COMMANDTIMEOUT = 20; DATABASE = es-template-db; PASSWORD = postgres; USER ID = postgres
      - RabbitMQConfiguration__UserName=admin
      - RabbitMQConfiguration__Password=admin
      - RabbitMQConfiguration__Host=rabbitmq
      - Serilog__WriteTo__1__Name=Seq
      - Serilog__WriteTo__1__Args__serverUrl=http://seq:80

  postgres:
    volumes:
      - ./build/docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
