version: "3.9"

services:
  naga.gateway:
    image: ${REGISTRY:-nikiforovall}/naga-gateway:${TAG:-latest}
    build:
      context: na-ga
      dockerfile: src/Gateway/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "3000:80"
    volumes:
      - ./routes.conf.json:/app/routes.conf.json

  naca.api:
    image: ${REGISTRY:-nikiforovall}/naca-api:${TAG:-latest}
    build:
      context: na-ca
      dockerfile: src/Api/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5000:80"
    depends_on:
      - rabbitmq
      - postgres

  naca.worker:
    image: ${REGISTRY:-nikiforovall}/naca-worker:${TAG:-latest}
    build:
      context: na-ca
      dockerfile: src/Worker/Dockerfile
    depends_on:
      - rabbitmq
      - postgres

  naes.api:
    image: ${REGISTRY:-nikiforovall}/naes-api:${TAG:-latest}
    build:
      context: na-es
      dockerfile: src/Api/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5001:80"
    depends_on:
      - rabbitmq
      - postgres

  naes.worker:
    image: ${REGISTRY:-nikiforovall}/naes-worker:${TAG:-latest}
    build:
      context: na-es
      dockerfile: src/Worker/Dockerfile
    depends_on:
      - rabbitmq
      - postgres

  rabbitmq:
    image: rabbitmq:3.8-management
  
  postgres:
    image: postgres:14.0
