version: "3.9"

services:
  naca-unit-tests:
    image: ${REGISTRY:-nikiforovall}/naca-test-unit:${TAG:-latest}
    build:
      context: na-ca
      dockerfile: src/Api/Dockerfile
      target: unittest
    volumes:
      - ${BUILD_ARTIFACTSTAGINGDIRECTORY:-./artifacts/}:/tests

  naca-integration-tests:
    image: ${REGISTRY:-nikiforovall}/naca-test-integration:${TAG:-latest}
    build:
      context: na-ca
      dockerfile: src/Api/Dockerfile
      target: integrationtest
    volumes:
      - ${BUILD_ARTIFACTSTAGINGDIRECTORY:-./artifacts/}:/tests
    depends_on:
      - postgres

  naes-unit-tests:
    image: ${REGISTRY:-nikiforovall}/naes-test-unit:${TAG:-latest}
    build:
      context: na-es
      dockerfile: src/Api/Dockerfile
      target: unittest
    volumes:
      - ${BUILD_ARTIFACTSTAGINGDIRECTORY:-./artifacts/}:/tests

  naes-integration-tests:
    image: ${REGISTRY:-nikiforovall}/naes-test-integration:${TAG:-latest}
    build:
      context: na-es
      dockerfile: src/Api/Dockerfile
      target: integrationtest
    volumes:
      - ${BUILD_ARTIFACTSTAGINGDIRECTORY:-./artifacts/}:/tests
    depends_on:
      - postgres

  postgres:
    image: postgres:14.0
    hostname: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
