name: .NET

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.100
    - name: Restore dependencies
      run: dotnet restore ./NikiforovAll.CleanArchitecture.Template.sln
    - name: Build
      run: dotnet build --no-restore ./NikiforovAll.CleanArchitecture.Template.sln
    - name: Test
      run: dotnet test --no-build --verbosity normal ./NikiforovAll.CleanArchitecture.Template.sln --filter Category!=Integration
